apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metal-lb
patches:
  - target:
      kind: IPAddressPool
      name: platform-pool
    patch: |
      - op: replace
        path: /spec/addresses
        value: ["10.10.10.50-10.10.10.60"]