; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL    86400
@       IN      SOA     lab.pl. root.lab.pl. (
                       20260606         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
        IN      NS      ns1.lab.pl.
ns1     IN      A       10.0.1.4
        IN      NS      ns2.lab.pl.
ns2     IN      A       10.0.1.5
;       IN      MX      10 mail.lab.pl

ns1.lab.pl      IN      A       10.0.1.4
10.0.1.4        IN      PTR     ns1.lab.pl.
ns2.lab.pl      IN      A       10.0.1.5
10.0.1.5        IN      PTR     ns2.lab.pl.

;Hostname
pr-dns1          IN      A       10.0.1.4
pr-dns2          IN      A       10.0.1.5
pr-lb1           IN      A       10.0.2.13
pr-lb2           IN      A       10.0.2.14
pr-rp1           IN      A       10.0.2.15
pr-rp2           IN      A       10.0.2.16
ca               IN      A       10.0.0.6
nfs              IN      A       10.0.0.10       
minio1           IN      A       10.0.0.18
minio2           IN      A       10.0.0.19
db1              IN      A       10.0.0.28
db2              IN      A       10.0.0.29
bastion          IN      A       10.0.0.109
pr-kube-m1       IN      A       10.0.0.110
pr-kube-m2       IN      A       10.0.0.111
pr-kube-m3       IN      A       10.0.0.112
pr-kube-w1       IN      A       10.0.0.113
pr-kube-w2       IN      A       10.0.0.114
pr-kube-w3       IN      A       10.0.0.115

;ReverseProxy
www.p-rt1       IN      A       10.0.0.1
p-rt1           IN      A       10.0.0.1
www.p-ap1       IN      A       10.0.1.250
p-ap1           IN      A       10.0.1.250
www.pve0        IN      A       10.0.0.2
pve0            IN      A       10.0.0.2
www.pve1        IN      A       10.0.0.3
pve1            IN      A       10.0.0.3
www.pve2        IN      A       10.0.0.4
pve2            IN      A       10.0.0.4
www.minio       IN      A       10.0.0.12
minio           IN      A       10.0.0.12
www.s3-minio    IN      A       10.0.0.12
s3-minio        IN      A       10.0.0.12
api-kube        IN      A       10.0.2.49
www.argocd      IN      A       10.0.7.240
argocd          IN      A       10.0.7.240
www.git         IN      A       10.0.7.240
git             IN      A       10.0.7.240
www.grafana     IN      A       10.0.7.240
grafana         IN      A       10.0.7.240        
www.iam         IN      A       10.0.7.240
iam             IN      A       10.0.7.240
www.jenkins     IN      A       10.0.7.240
jenkins         IN      A       10.0.7.240
www.nexus       IN      A       10.0.7.240
nexus           IN      A       10.0.7.240
