all:
  children:
    dc:
      hosts:
        pve0:
          ansible_host: 10.0.0.2
          ssh_port: 22
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox
          ansible_become: false
        pve1:
          ansible_host: 10.0.0.3
          ssh_port: 22
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox
          ansible_become: false
        pve2:
          ansible_host: 10.0.0.4
          ssh_port: 22
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox
          ansible_become: false
    dns:
      hosts: 
        dns_master:
          ansible_host: p-dns1.lab.pl
          ssh_port: 22
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_mikrus
          ansible_become: true
        dns_slave:
          ansible_host: p-dns2.lab.pl
          ssh_port: 22
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_mikrus
          ansible_become: true
    load_balancer:
      hosts:
        lb_master:
          ansible_host: p-lb1.lab.pl
          ssh_port: 22
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_mikrus
          ansible_become: true
        lb_slave:
          ansible_host: p-lb2.lab.pl
          ssh_port: 22
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_mikrus
          ansible_become: true
