#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Create user
  ansible.builtin.user:
    name: "{{ common_user }}"
    comment: Administrator
    shell: /bin/bash
    expires: -1
  when: "'lxc' in group_names"
