#SPDX-License-Identifier: MIT-0
---
# tasks file for lxc_ssh
- name: Get list of LXC containers
  ansible.builtin.command: lxc-ls --quiet
  register: lxc_containers
  tags: lxc
  changed_when: false

- name: Show LXC container IDs
  ansible.builtin.debug:
    var: lxc_containers.stdout_lines
  tags: lxc

- name: Debug which containers host sees
  ansible.builtin.debug:
    msg: "Host {{ inventory_hostname }} keeps: {{ hostvars[inventory_hostname]['lxc_containers']['stdout_lines'] }}"
  tags: lxc

- name: Check if OpenSSH server is installed
  ansible.builtin.command: lxc-attach --quiet -n {{ item }} -- rpm -q openssh-server
  loop: "{{ hostvars[inventory_hostname]['lxc_containers']['stdout_lines'] }}"
  register: ssh_check
  ignore_errors: true
  tags: lxc
  changed_when: false
  failed_when: >
    ansible.builtin.command: item.rc != 0 

- name: Install OpenSSH server
  ansible.builtin.command: lxc-attach --quiet -n {{ item.item }} -- yum install -y openssh-server
  #loop: "{{ hostvars[inventory_hostname]['lxc_containers']['stdout_lines'] }}"
  loop: "{{ ssh_check.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.rc != 0
  failed_when: >
    ansible.builtin.command: item.rc != 0 
  tags: lxc
  changed_when: false

- name: Start OpenSSH server
  ansible.builtin.command: lxc-attach --quiet -n {{ item.item }} -- systemctl start sshd.service
  #loop: "{{ hostvars[inventory_hostname]['lxc_containers']['stdout_lines'] }}"
  loop: "{{ ssh_check.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.rc != 0
  tags: lxc
  failed_when: >
    ansible.builtin.command: item.rc != 0 
  changed_when: false
