#SPDX-License-Identifier: MIT-0
---
# tasks file for dns
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dns_packages }}"
  when: dns_packages is defined and dns_packages | length > 0 #and inventory_hostname in groups['dns']
  tags: deploy

- name: Copy DNS zone file
  ansible.builtin.copy:
    src: "files/db.lab.pl"
    dest: "/etc/named/"
    owner: root
    group: root
    mode: '0644'
  #when: inventory_hostname in groups['dns']
  tags: deploy, update

- name: Copy reverse DNS zone files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/named/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "db.10.0.0"
    - "db.10.0.1"
    - "db.10.0.2"
    - "db.10.0.3"
    - "db.10.0.4"
    - "db.10.0.5"
    - "db.10.0.6"
    - "db.10.0.7"
  #when: inventory_hostname in groups['dns']
  tags: deploy, update

- name: Copy zone configuration file
  ansible.builtin.copy:
    src: "files/named.conf.local"
    dest: "/etc/named/"
    owner: root
    group: root
    mode: '0644'
  #when: inventory_hostname in groups['dns']
  tags: deploy, update

- name: Copy configuration files for BIND primary
  ansible.builtin.copy:
    src: "files/named-primary.conf"
    dest: "/etc/named.conf"
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "dns-master"
  tags: deploy, update

- name: Copy configuration files for BIND secondary
  ansible.builtin.copy:
    src: "files/named-secondary.conf"
    dest: "/etc/named.conf"
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "dns-slave"
  tags: deploy, update

- name: Start and enable BIND service
  ansible.builtin.systemd:
    name: named
    state: restarted
    enabled: yes
  #when: inventory_hostname in groups['dns']
  tags: deploy, update
