- name: Deploy DNS services
  ansible.builtin.import_playbook: playbook/dns.yml
- name: Configure SSH on LXC containers
  ansible.builtin.import_playbook: playbook/lxc_common.yml
#- name: Deploy DNS services
#  ansible.builtin.import_playbook: playbook/dns.yml
- name: Apply common configurations
  ansible.builtin.import_playbook: playbook/common.yml
- name: Hardening
  ansible.builtin.import_playbook: playbook/hardening.yml
