#- ansible.builtin.import_playbook: playbook/proxmox_ssh.yml
#- ansible.builtin.import_playbook: playbook/lxc_ssh.yml
#- ansible.builtin.import_playbook: playbook/common.yml
- name: Configure DNS servers
  ansible.builtin.import_playbook: playbook/dns.yml
