apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      targetRevision: 12.3.1
      chart: grafana
      helm:
        valueFiles:
          - $values/values/grafana.yml
    - repoURL: http://git.lab.pl/HomeLab/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
