---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify
  hosts: all
  gather_facts: true # Quicker, if you do not need facts
  tasks:
    - name: Load default variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../defaults/main.yml"

    - name: Load common variables
      ansible.builtin.include_vars: 
        file: "{{ playbook_dir }}/../../vars/{{ ansible_facts['os_family'] }}.yml"
    
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if common packages are installed
      ansible.builtin.assert:
        that:
          - item in ansible_facts.packages
        fail_msg: "{{ item }} package is not installed"
      loop: "{{ common_packages }}"

    - name: Get timezone
      ansible.builtin.command: timedatectl show --property=Timezone --value
      register: tz_check
      changed_when: false

    - name: Check timezone is set correctly
      ansible.builtin.assert:
        that:
          - tz_check.stdout == common_timezone
        fail_msg: "Timezone is {{ tz_check.stdout }}, expected {{ common_timezone }}"