apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bootstrap/
  - ../../base/namespaces
patches:
  - target:
      kind: Application
      name: kubernetes
    patch: |
      - op: replace
        path: /spec/source/targetRevision
        value: $BRANCH
