name: Ansible Checks

on:
  push:
    branches:
      - main
      - dev
      - prod
  pull_request:
    types: 
      - opened
      - synchronize
      - edited

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Setup Ansible
        working-directory: ansible
        run: |
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Ansible syntax check
        working-directory: ansible
        run: ansible-playbook site.yml --syntax-check

      - name: Ansible lint
        working-directory: ansible
        run: ansible-lint
